// Package x402types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package x402types

// Authorization EIP-3009 transferWithAuthorization arguments the caller signed.
type Authorization struct {
	// From payer address (hex)
	From string `json:"from"`

	// Nonce authorization nonce (hex)
	Nonce string `json:"nonce"`

	// To recipient address (hex)
	To string `json:"to"`

	// ValidAfter unix seconds
	ValidAfter string `json:"validAfter"`

	// ValidBefore unix seconds
	ValidBefore string `json:"validBefore"`

	// Value amount
	Value string `json:"value"`
}

// Payment The decoded X-PAYMENT header for the `exact` scheme.
type Payment struct {
	Network string `json:"network"`

	// Payload The `exact`-scheme payload — signature over the authorization.
	Payload     PaymentPayload `json:"payload"`
	Scheme      string         `json:"scheme"`
	X402Version int            `json:"x402Version"`
}

// PaymentPayload The `exact`-scheme payload — signature over the authorization.
type PaymentPayload struct {
	// Authorization EIP-3009 transferWithAuthorization arguments the caller signed.
	Authorization Authorization `json:"authorization"`
	Signature     string        `json:"signature"`
}

// PaymentRequirements One entry of a 402 challenge's `accepts` array.
type PaymentRequirements struct {
	// Asset token contract address (hex)
	Asset string `json:"asset"`

	// MaxAmountRequired decimal string (256-bit)
	MaxAmountRequired string `json:"maxAmountRequired"`
	MaxTimeoutSeconds int    `json:"maxTimeoutSeconds"`
	Network           string `json:"network"`
	PayTo             string `json:"payTo"`
	Resource          string `json:"resource"`
	Scheme            string `json:"scheme"`
}

// SettleRequest POST /settle request body — verified payment handed to the facilitator.
type SettleRequest struct {
	// PaymentPayload The decoded X-PAYMENT header for the `exact` scheme.
	PaymentPayload Payment `json:"paymentPayload"`

	// PaymentRequirements One entry of a 402 challenge's `accepts` array.
	PaymentRequirements PaymentRequirements `json:"paymentRequirements"`
	X402Version         int                 `json:"x402Version"`
}

// SettleResponse POST /settle response body. facilitatorFee is an optional extension a fee-recovering facilitator may report; absent on a self-hosted one.
type SettleResponse struct {
	ErrorReason    string `json:"errorReason,omitempty"`
	FacilitatorFee string `json:"facilitatorFee,omitempty"`
	Network        string `json:"network,omitempty"`
	Payer          string `json:"payer,omitempty"`
	Success        bool   `json:"success"`
	Transaction    string `json:"transaction,omitempty"`
}
