package config

import (
	"fmt"
	"strings"
)

// generatedBanner marks the emitted file as machine-generated. It is an HTML
// comment so it does not render on the docs page, but warns anyone who opens
// the file directly.
const generatedBanner = "<!-- GENERATED by `make -C gateway docs` from " +
	"gateway/internal/config/reference.go — do not edit by hand. -->"

// RenderMarkdown renders Reference as a Markdown fragment: one table per group,
// in Groups order, preceded by the generated banner. The output is a Starlight
// partial (imported by the configuration reference page), not a standalone
// page, so it carries no frontmatter.
func RenderMarkdown() []byte {
	var b strings.Builder
	b.WriteString(generatedBanner)
	b.WriteString("\n")

	for _, group := range Groups {
		vars := varsInGroup(group)
		if len(vars) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n### %s\n\n", group)
		b.WriteString("| Variable | Required | Default | Description |\n")
		b.WriteString("| --- | --- | --- | --- |\n")
		for _, v := range vars {
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
				variableCell(v), requiredCell(v), defaultCell(v), v.Description)
		}
	}

	return []byte(b.String())
}

func varsInGroup(group string) []Var {
	var out []Var
	for _, v := range Reference {
		if v.Group == group {
			out = append(out, v)
		}
	}
	return out
}

func variableCell(v Var) string {
	cell := "`" + v.Name + "`"
	for _, alias := range v.Aliases {
		cell += "<br />or `" + alias + "`"
	}
	return cell
}

func requiredCell(v Var) string {
	if v.Required {
		return "Yes"
	}
	return "No"
}

func defaultCell(v Var) string {
	if !v.HasDefault {
		return "—"
	}
	if v.Default == "" {
		return "`\"\"`"
	}
	return "`" + v.Default + "`"
}
